# Generated by Django 2.1.7 on 2019-03-21 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Email',
            field=models.EmailField(max_length=255, null=True, unique=True, verbose_name='E-mail'),
        ),
        migrations.AddField(
            model_name='user',
            name='Password',
            field=models.CharField(max_length=128, null=True, verbose_name='Пароль'),
        ),
    ]
