# Generated by Django 2.1.7 on 2019-03-21 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_auto_20190321_0659'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='Email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='Password',
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=255, null=True, unique=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=128, null=True, verbose_name='Пароль'),
        ),
    ]
