# Generated by Django 2.1.7 on 2019-03-21 03:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AddList', '0002_remove_add_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='add',
            old_name='Added',
            new_name='PostingDate',
        ),
        migrations.AlterField(
            model_name='add',
            name='Author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adds', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
    ]
